name: Build Docker image

on:
  push:
    branches:
      - main
      - test
      - workflow_dispatch

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: update
      run: sudo apt-get update && sudo apt-get install -y sshpass
  
    - name: connect and pull
      run: sshpass -p 'Azure@123456' scp -o PreferredAuthentications=password -r ./* docker-user@20.244.6.142:~/home/docker-user/docker_work_dir/
  
    - name: Docker run
      run: docker compose up

      
