name: Build Docker image

on:
  push:
    branches:
      - main
      - test
      - workflow_dispatch

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: update
      run: sudo apt-get update && sudo apt-get install -y sshpass
  
    - name: connect and pull
      run: sshpass -p ${{ secrets.SSH_PASSWORD }} scp -o PreferredAuthentications=password -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/docker_work_dir/
  
    - name: Docker run
      run: docker compose up

      
