name: Build Docker image

on:
  push:
    branches:
      - main
      - test
      - workflow_dispatch

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: update
      run: sudo apt-get update 
  
    - name: connect and pull
      run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 
  
    - name: Docker run
      run: docker compose up

      
